all:
  vars:
    ansible_user: ansible
    ansible_password: ansible
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

  hosts:
    debian1:
      ansible_host: 127.0.0.1
      ansible_port: 2221
    debian2:
      ansible_host: 127.0.0.1
      ansible_port: 2222
    oraclelinux2:
      ansible_host: 127.0.0.1
      ansible_port: 2223
