services:
  debian1:
    build: .
    container_name: debian1
    hostname: debian1
    # Donne au container toutes les capabilities Linux
    privileged: true
    ports:
      - "2221:22"
      - "8080:80"
    networks:
      - ansible-net
    # besoin d'écrire dans /run et /run/lock au démarragete
    tmpfs:
      - /run
      - /run/lock
    # Partage le namespace cgroup de l'hôte
    cgroup: host
    # Monte le filesystem cgroup de l'hôte en lecture/écriture
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

  debian3:
    build: .
    container_name: debian3
    hostname: debian3
    privileged: true
    ports:
      - "2222:22"
      - "8081:80"
    networks:
      - ansible-net
    tmpfs:
      - /run
      - /run/lock
    cgroup: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

networks:
  ansible-net:
    driver: bridge
